# Generated by Django 3.2.16 on 2023-05-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_firm333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firm333',
        ),
    ]
