# Generated by Django 4.1 on 2022-10-08 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_charge_remove_reservation_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='capacity',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='audi', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='connection_value',
            field=models.CharField(default='2', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='model_year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connection',
            name='status',
            field=models.CharField(default='available', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='charge',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.charge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='capacity',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='off_time',
            field=models.CharField(default='2', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='on_time',
            field=models.CharField(default='2', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='status',
            field=models.CharField(default='available', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='turkey', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='5312224435', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Statiom_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AC', models.IntegerField()),
                ('DC', models.IntegerField()),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.station')),
            ],
        ),
        migrations.CreateModel(
            name='favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField()),
                ('delete_time', models.DateTimeField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address_line', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
