# Generated by Django 4.1 on 2022-10-10 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_connection_capacity_car_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='users.firm'),
        ),
    ]
