# Generated by Django 4.1 on 2022-10-10 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_statiom_price_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statiom_price',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_prices', to='users.station'),
        ),
    ]
