# Generated by Django 4.1 on 2022-10-10 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_statiom_price_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AC', models.IntegerField()),
                ('DC', models.IntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='users.station')),
            ],
        ),
        migrations.DeleteModel(
            name='Statiom_Price',
        ),
    ]
