# Generated by Django 4.1 on 2022-10-11 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_station_price_delete_statiom_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='location',
        ),
        migrations.AlterField(
            model_name='connection',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='users.station'),
        ),
        migrations.AlterField(
            model_name='station_price',
            name='station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.station'),
        ),
        migrations.CreateModel(
            name='Station_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_adress', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.station')),
            ],
        ),
    ]
