# Generated by Django 4.1 on 2022-10-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_station_location_alter_connection_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='kiani', max_length=255),
            preserve_default=False,
        ),
    ]
