# Generated by Django 4.1 on 2022-10-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('total_range', models.CharField(max_length=255)),
                ('connection_type', models.CharField(max_length=255)),
                ('connection_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='car',
            name='connection_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='connection_value',
        ),
        migrations.RemoveField(
            model_name='car',
            name='total_range',
        ),
        migrations.AddField(
            model_name='car',
            name='car',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.car_list'),
            preserve_default=False,
        ),
    ]
