# Generated by Django 4.1 on 2022-10-12 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_car_list_remove_car_brand_remove_car_connection_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='address_line',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='adress',
            old_name='location',
            new_name='country',
        ),
        migrations.AddField(
            model_name='adress',
            name='full_adress',
            field=models.CharField(default='Fikirtepe mahallesi, Yıldırım Sokak No:40, A blok, Daire:50', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='latitude',
            field=models.CharField(default='40.0023', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='longitude',
            field=models.CharField(default='50.0029', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.car_list'),
        ),
    ]
