# Generated by Django 4.1 on 2022-10-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_address_line_adress_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='delete_time',
        ),
    ]
