# Generated by Django 4.1 on 2022-10-12 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_favorites_add_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_list', to='users.car_list'),
        ),
    ]
