# Generated by Django 4.1 on 2022-10-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_car_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carss', to='users.car_list'),
        ),
    ]
