# Generated by Django 4.1 on 2023-04-03 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_car_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='areas',
            fields=[
                ('areaid', models.IntegerField(primary_key=True, serialize=False)),
                ('countyid', models.IntegerField(null=True)),
                ('areaname', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cities',
            fields=[
                ('cityid', models.IntegerField(primary_key=True, serialize=False)),
                ('countryid', models.IntegerField(null=True)),
                ('cityname', models.CharField(max_length=100, null=True)),
                ('plateno', models.CharField(max_length=2, null=True)),
                ('phonecode', models.CharField(max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='counties',
            fields=[
                ('countyid', models.IntegerField(primary_key=True, serialize=False)),
                ('cityid', models.IntegerField(null=True)),
                ('countyname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='countries',
            fields=[
                ('countryid', models.IntegerField(primary_key=True, serialize=False)),
                ('binarycode', models.CharField(max_length=2, null=True)),
                ('triplecode', models.CharField(max_length=3, null=True)),
                ('countryname', models.CharField(max_length=100, null=True)),
                ('phonecode', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='neighborhoods',
            fields=[
                ('neighborhoodid', models.IntegerField(primary_key=True, serialize=False)),
                ('areaid', models.IntegerField(null=True)),
                ('neighborhoodname', models.CharField(max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='adress',
            name='country',
        ),
        migrations.AddField(
            model_name='charge',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.connection'),
        ),
        migrations.AddField(
            model_name='connection',
            name='connection_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.connection'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserv_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='full_adress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='latitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='longitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='battery_health',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carss', to='users.car_list'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car_list',
            name='brand',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='car_list',
            name='connection_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='car_list',
            name='connection_value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='car_list',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='car_list',
            name='total_range',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='reservation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.reservation'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.station'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connection',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='power',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='users.station'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.station'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='firm',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='charge',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.charge'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.payment'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='charge',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.charge'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.station'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='station',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='users.firm'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='off_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='on_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station_location',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station_location',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station_location',
            name='full_adress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station_location',
            name='latitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station_location',
            name='longitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station_location',
            name='station',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.station'),
        ),
        migrations.AlterField(
            model_name='station_price',
            name='AC',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='station_price',
            name='DC',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='station_price',
            name='station',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.station'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.car'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='range',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='counties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.counties'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cities'),
        ),
    ]
